### ISSUE TITLE
防止1 3连接跳过2以及3 9连接跳过5 

### ISSUE THREAD

**Issue by IHansan** [ihsg/PatternLocker#15]
private void updateHitState(MotionEvent event) {
        final float x = event.getX();
        final float y = event.getY();
        for (CellBean c : this.cellBeanList) {
            if (!c.isHit && c.of(x, y)) {
                if (hitList.size() > 0) {
                    CellBean lastHit = null;
                    for (int i = 0; i < cellBeanList.size(); i++) {
                        if (cellBeanList.get(i).id == hitList.get(hitList.size() - 1)) {
                            lastHit = cellBeanList.get(i);
                            break;
                        }
                    }
                    if (lastHit != null) {
                        if (Math.abs(c.x - lastHit.x) == Math.abs(c.y - lastHit.y)) {
                            if (lastHit.x > c.x) {
                                for (CellBean c1 : this.cellBeanList) {
                                    if (!c1.isHit && c1.of(c.x + (lastHit.x - c.x) / 2, c.y + (lastHit.y - c.y) / 2)) {
                                        c1.isHit = true;
                                        this.hitList.add(c1.id);
                                    }
                                }
                            } else {
                                for (CellBean c1 : this.cellBeanList) {
                                    if (!c1.isHit && c1.of(lastHit.x + (c.x - lastHit.x) / 2, lastHit.y + (c.y - lastHit.y) / 2)) {
                                        c1.isHit = true;
                                        this.hitList.add(c1.id);
                                    }
                                }
                            }
                        } else if (Math.abs(c.x - lastHit.x) > Math.abs(c.y - lastHit.y)) {
                            if (lastHit.x > c.x) {
                                //处理斜线 2-7 2-9这种
                                if (c.y == lastHit.y) {
                                    for (CellBean c1 : this.cellBeanList) {
                                        if (!c1.isHit && c1.of(c.x + (lastHit.x - c.x) / 2, c.y)) {
                                            c1.isHit = true;
                                            this.hitList.add(c1.id);
                                        }
                                    }
                                } else if (lastHit.y > c.y) {
                                    for (CellBean c1 : this.cellBeanList) {
                                        if (!c1.isHit && c1.of(c.x + (lastHit.x - c.x) / 2, c.y + (lastHit.y - c.y) / 2)) {
                                            c1.isHit = true;
                                            this.hitList.add(c1.id);
                                        }
                                    }
                                } else {
                                    for (CellBean c1 : this.cellBeanList) {
                                        if (!c1.isHit && c1.of(c.x + (lastHit.x - c.x) / 2, lastHit.y + (c.y - lastHit.y) / 2)) {
                                            c1.isHit = true;
                                            this.hitList.add(c1.id);
                                        }
                                    }
                                }

                            } else {
                                if (c.y == lastHit.y) {
                                    for (CellBean c1 : this.cellBeanList) {
                                        if (!c1.isHit && c1.of(lastHit.x + (c.x - lastHit.x) / 2, c.y)) {
                                            c1.isHit = true;
                                            this.hitList.add(c1.id);
                                        }
                                    }
                                } else if (lastHit.y > c.y) {
                                    for (CellBean c1 : this.cellBeanList) {
                                        if (!c1.isHit && c1.of(lastHit.x + (c.x - lastHit.x) / 2, c.y + (lastHit.y - c.y) / 2)) {
                                            c1.isHit = true;
                                            this.hitList.add(c1.id);
                                        }
                                    }
                                } else {
                                    for (CellBean c1 : this.cellBeanList) {
                                        if (!c1.isHit && c1.of(lastHit.x + (c.x - lastHit.x) / 2, lastHit.y + (c.y - lastHit.y) / 2)) {
                                            c1.isHit = true;
                                            this.hitList.add(c1.id);
                                        }
                                    }
                                }
                            }
                        } else {
                            if (lastHit.y > c.y) {
                                if (lastHit.x == c.x) {
                                    for (CellBean c1 : this.cellBeanList) {
                                        if (!c1.isHit && c1.of(c.x, c.y + (lastHit.y - c.y) / 2)) {
                                            c1.isHit = true;
                                            this.hitList.add(c1.id);
                                        }
                                    }
                                } else if (lastHit.x > c.x) {
                                    for (CellBean c1 : this.cellBeanList) {
                                        if (!c1.isHit && c1.of(c.x + (lastHit.x - c.x) / 2, c.y + (lastHit.y - c.y) / 2)) {
                                            c1.isHit = true;
                                            this.hitList.add(c1.id);
                                        }
                                    }
                                } else {
                                    for (CellBean c1 : this.cellBeanList) {
                                        if (!c1.isHit && c1.of(lastHit.x + (c.x - lastHit.x) / 2, c.y + (lastHit.y - c.y) / 2)) {
                                            c1.isHit = true;
                                            this.hitList.add(c1.id);
                                        }
                                    }
                                }

                            } else {
                                if (lastHit.x == c.x) {
                                    for (CellBean c1 : this.cellBeanList) {
                                        if (!c1.isHit && c1.of(c.x, lastHit.y + (c.y - lastHit.y) / 2)) {
                                            c1.isHit = true;
                                            this.hitList.add(c1.id);
                                        }
                                    }
                                } else if (lastHit.x > c.x) {
                                    for (CellBean c1 : this.cellBeanList) {
                                        if (!c1.isHit && c1.of(c.x + (lastHit.x - c.x) / 2, lastHit.y + (c.y - lastHit.y) / 2)) {
                                            c1.isHit = true;
                                            this.hitList.add(c1.id);
                                        }
                                    }
                                } else {
                                    for (CellBean c1 : this.cellBeanList) {
                                        if (!c1.isHit && c1.of(lastHit.x + (c.x - lastHit.x) / 2, lastHit.y + (c.y - lastHit.y) / 2)) {
                                            c1.isHit = true;
                                            this.hitList.add(c1.id);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                c.isHit = true;
                this.hitList.add(c.id);
            }
        }
    }

**Comment by ihsg** [comment]
@IHansan 你这个太复杂了
