### ISSUE TITLE
空指针了

### ISSUE THREAD

**Issue by 247033993** [ihsg/PatternLocker#16]
java.lang.NullPointerException
Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference

1 com.github.ihsg.patternlocker.PatternLockerView.updateHitState(PatternLockerView.java:340)
--
2 com.github.ihsg.patternlocker.PatternLockerView.handleActionDown(PatternLockerView.java:296)
3 com.github.ihsg.patternlocker.PatternLockerView.onTouchEvent(PatternLockerView.java:212)
4 android.view.View.dispatchTouchEvent(View.java:11843)
5 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2981)
6 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2611)
7 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2981)
8 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2611)
9 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2981)
10 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2611)
11 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2981)
12 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2611)
13 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2981)
14 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2611)
15 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2981)
16 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2611)
17 com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:552)
18 com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1959)
19 android.app.Activity.dispatchTouchEvent(Activity.java:3526)
20 android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
21 com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:505)
22 android.view.View.dispatchPointerEvent(View.java:12082)
23 android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5325)
24 android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5109)
25 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4623)
26 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4676)
27 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4642)
28 android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4769)
29 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4650)
30 android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4826)
31 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4623)
32 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4676)
33 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4642)
34 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4650)
35 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4623)
36 android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7222)
37 android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7196)
38 android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7157)
39 android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7379)
40 android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:193)
41 android.os.MessageQueue.nativePollOnce(Native Method)
42 android.os.MessageQueue.next(MessageQueue.java:379)
43 android.os.Looper.loop(Looper.java:144)
44 android.app.ActivityThread.main(ActivityThread.java:7383)
45 java.lang.reflect.Method.invoke(Native Method)
46 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
47 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

**Comment by ihsg** [comment]
@247033993 谢谢反馈，请问用的是最新版本么？

**Comment by 247033993** [comment]
com.github.ihsg:PatternLocker:2.1.0

**Comment by 247033993** [comment]
这个可以修复吗

**Comment by ihsg** [comment]
@247033993 请用2.2.0最新版本哈
