### ISSUE TITLE
bug数组下标越界

### ISSUE THREAD

**Issue by zwonb** [ihsg/PatternLocker#18]
在三星s4的手机上面会报错，系统5.0.1
Invalid index 1122041856, size is 9

com.github.ihsg.patternlocker.h.a(DefaultLockerLinkedLineView.java:70)

`

1 java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
--
2 java.util.ArrayList.get(ArrayList.java:308)
3 com.github.ihsg.patternlocker.h.a(DefaultLockerLinkedLineView.java:70)
4 com.github.ihsg.patternlocker.PatternLockerView.a(PatternLockerView.java:261)
5 com.github.ihsg.patternlocker.PatternLockerView.onDraw(PatternLockerView.java:199)
6 android.view.View.draw(View.java:16219)
7 android.view.View.updateDisplayListIfDirty(View.java:15139)
8 android.view.View.getDisplayList(View.java:15162)
9 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
10 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
11 android.view.View.updateDisplayListIfDirty(View.java:15099)
12 android.view.View.getDisplayList(View.java:15162)
13 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
14 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
15 android.view.View.updateDisplayListIfDirty(View.java:15099)
16 android.view.View.getDisplayList(View.java:15162)
17 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
18 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
19 android.view.View.updateDisplayListIfDirty(View.java:15099)
20 android.view.View.getDisplayList(View.java:15162)
21 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
22 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
23 android.view.View.updateDisplayListIfDirty(View.java:15099)
24 android.view.View.getDisplayList(View.java:15162)
25 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
26 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
27 android.view.View.updateDisplayListIfDirty(View.java:15099)
28 android.view.View.getDisplayList(View.java:15162)
29 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
30 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
31 android.view.View.updateDisplayListIfDirty(View.java:15099)
32 android.view.View.getDisplayList(View.java:15162)
33 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
34 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
35 android.view.View.updateDisplayListIfDirty(View.java:15099)
36 android.view.View.getDisplayList(View.java:15162)
37 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
38 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
39 android.view.View.updateDisplayListIfDirty(View.java:15099)
40 android.view.View.getDisplayList(View.java:15162)
41 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
42 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
43 android.view.View.updateDisplayListIfDirty(View.java:15099)
44 android.view.View.getDisplayList(View.java:15162)
45 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
46 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
47 android.view.View.updateDisplayListIfDirty(View.java:15099)
48 android.view.View.getDisplayList(View.java:15162)
49 android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:275)
50 android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:281)
51 android.view.ThreadedRenderer.draw(ThreadedRenderer.java:320)
52 android.view.ViewRootImpl.draw(ViewRootImpl.java:2751)
53 android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2584)
54 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2176)
55 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
56 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6642)
57 android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
58 android.view.Choreographer.doCallbacks(Choreographer.java:590)
59 android.view.Choreographer.doFrame(Choreographer.java:560)
60 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
61 android.os.Handler.handleCallback(Handler.java:739)
62 android.os.Handler.dispatchMessage(Handler.java:95)
63 android.os.Looper.loop(Looper.java:145)
64 android.app.ActivityThread.main(ActivityThread.java:5951)
65 java.lang.reflect.Method.invoke(Native Method)
66 java.lang.reflect.Method.invoke(Method.java:372)
67 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
68 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

`

**Comment by zwonb** [comment]
2.1.0报错，升级到2.2.0也报错

**Comment by ihsg** [comment]
@zwonb 谢谢反馈，必现的bug么？请问怎么操作会出现这个错误？

**Comment by zwonb** [comment]
@ihsg 随便点一下就报错了，赶紧修复一下吧！app已经上线好久了 三星的用户反馈这个问题。。。

**Comment by ihsg** [comment]
@zwonb 好了，更新下

**Comment by zwonb** [comment]
还是会出现此问题 @ihsg

**Comment by ihsg** [comment]
@zwonb 不可能的，我加了检测，你确定你更新了么？

**Comment by zwonb** [comment]
是的已经更新了，在我的手机也是一直没出现问题！但是在三星s4手机就出问题，我觉得你可以去三星s4手机上测试一下！@ihsg

**Comment by ihsg** [comment]
@zwonb 再更新下，只能才代码层面防御了，但是原因不清楚，我没有那个手机，所以没法debug，如果你方便的话，帮忙debug一下，看看为啥会这样！另外错误栈可以去混淆么，这样定位更快一些！

**Comment by zwonb** [comment]
在三星s4手机上面 手指触摸的时候都不会让单个lockview重绘，一直显示默认的状态，你可以从viewgroup开始排查 @ihsg

**Comment by zwonb** [comment]
![image](https://user-images.githubusercontent.com/22101549/50743867-ac14a680-1257-11e9-95d8-bfc9ed77796b.png)

![image](https://user-images.githubusercontent.com/22101549/50743878-d8c8be00-1257-11e9-9b3f-62e3709c09cf.png)

还是在三星s4的手机上面，现在不会报错，但是绘制的线有问题

**Comment by zwonb** [comment]
@ihsg 忘记艾特

**Comment by ihsg** [comment]
@zwonb 麻烦帮忙debug一下看下什么问题，谢谢！

**Comment by zwonb** [comment]
@ihsg 我这也没有三星s4手机，我在第三方的测试平台测试的，所以不能debug了

**Comment by ihsg** [comment]
@zwonb 加我微信 15651012291
