### ISSUE TITLE
manifest冲突，Didn't find class "kotlin.reflect.KProperty"

### ISSUE THREAD

**Issue by devilived** [ihsg/PatternLocker#19]
在用java代码中引用     implementation 'com.github.ihsg:PatternLocker:2.4.0'遇到2个问题

1. 结果编译的时候报manifest冲突，lib中的manifest最好是空的。
2. 同时运行的时候报出 Didn't find class "kotlin.reflect.KProperty"，不知道该如何解决。

注：我是java使用者，对kotlin中的问题不太熟悉。

**Comment by ihsg** [comment]
@devilived 谢谢反馈，manifest冲突已经解决了，Didn't find class "kotlin.reflect.KProperty" 需要你配置kotlin开发环境就好了，谢谢！

**Comment by devilived** [comment]
经测，如果在java中只是调用该库，不用搭建完整的kotlin环境，只需添加 runtimeOnly org.jetbrains.kotlin:kotlin-stdlib${version}就行，jdk7或者jdk8的适配库都不需要。

**Comment by silencefly96** [comment]
你这个这么加，我这问题也是在这
