### ISSUE TITLE
PatternIndicatorView 如果不延时就立即updateState，会导致画不出来。

### ISSUE THREAD

**Issue by devilived** [ihsg/PatternLocker#21]
在Activitiy的oncreate中立即调用PatternIndicatorView.updateState初始化数据，会导致该组件空白。如果等待几秒，等他先画出来再调用就没事，应该是时序的问题。

**Comment by ihsg** [comment]
@devilived 不是很明白你的意思，PatternIndicatorView.updateState 不是初始化用的，是操纵指示器，配合PatternLockerView用的，具体请参考demo

**Comment by devilived** [comment]
是这样的，我们有这样的需求，就是用户一进来就要显示用户之前的图案密码，然后用户可以修改这个密码。 因此进入到页面就需要先用指示器显示出来。。。
