### ISSUE TITLE
我们要一进来就显示一个手势密码，然后再修改它。。

### ISSUE THREAD

**Issue by devilived** [ihsg/PatternLocker#25]
是这样的，我们有这样的需求，就是用户一进来就要显示用户之前的图案密码，然后用户可以修改这个密码。 因此进入到页面就需要先用指示器显示出来。。。

_Originally posted by @devilived in https://github.com/ihsg/PatternLocker/issues/21#issuecomment-482769534_

**Comment by ihsg** [comment]
@devilived 初始化完成调用updateState方法就可以了

**Comment by devilived** [comment]
class DefaultPatternSettingActivity : AppCompatActivity() {
    private var patternHelper: PatternHelper? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_default_pattern_setting)
        patternIndicatorView.updateState(Arrays.asList(1,2),false);

注意最后一行代码，如果加上这句话，那么patternIndicatorView就会消失。而如果延迟1s再执行这句话，就没事。

**Comment by ihsg** [comment]
@devilived 万分感谢反馈，现已修复，再次感谢！
