### ISSUE TITLE
PatternIndicatorView 的颜色不能改变

### ISSUE THREAD

**Issue by devilived** [ihsg/PatternLocker#26]
PatternIndicatorView的颜色无论是java调用  mPtnIndicator.setNormalColor（）还是xml配置 app:piv_color="@color/fontView"或者 app:plv_color="@color/fontView"，都不能生效，始终是蓝色的

**Comment by ihsg** [comment]
@devilived 请认真看使用说明，java设置你调用build方法了吗?xml配置肯定可以的， 除非你fontView设置有问题

**Comment by devilived** [comment]
xml的piv:color可以起作用，但是通过mPtnIndicator.setNormalColor不起作用，不知道piv:color对应方法是不是setNormalColor?

我使用方式是xml初始化view，在java代码中动态改变颜色。

**Comment by devilived** [comment]
应该是hitcolor用java代码设置不生效

**Comment by ihsg** [comment]
@devilived 万分感谢您的反馈，现在已经修复了
