### ISSUE TITLE
mPtnIndicator.updateState(null, false)不起作用

### ISSUE THREAD

**Issue by devilived** [ihsg/PatternLocker#27]
之前的版本是可以的，最新的不起作用。这个不算bug吧，用updateState(Collections.emptyList(), false)倒是可以的

**Comment by devilived** [comment]
另外demo中的this.patternIndicatorView.normalCellView as DefaultLockerNormalCellView这个应该是写错了，DefaultLockerNormalCellView应该是DefaultIndicatorNormalCellView

**Comment by ihsg** [comment]
@devilived 谢谢反馈，已经修复了！
