### ISSUE TITLE
一个闪退  UninitializedPropertyAccessException 

### ISSUE THREAD

**Issue by wangshunji** [ihsg/PatternLocker#32]
#5204 kotlin.UninitializedPropertyAccessException
lateinit property cellBeanList has not been initialized
com.github.ihsg.patternlocker.PatternLockerView.updateHitState(PatternLockerView.kt:272)

机型信息：
OPPO PBAM00   33.33%，
三星 SM G9550   33.33%，
OPPO PBBT00    33.33%，
系统版本 9占66.67% ，系统版本  8.1.0 占33.33%

**Comment by ihsg** [comment]
无法复现
