### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by dy175785** [ihsg/PatternLocker#34]
只设置了布局，进页面直接闪退，日志不报啥错

**Comment by ihsg** [comment]
@dy175785 谢谢反馈, 查到什么原因了吗?

**Comment by 843454898** [comment]
have bug
kotlin.UninitializedPropertyAccessException
lateinit property cellBeanList has not been initialized

com.github.ihsg.patternlocker.PatternLockerView.updateHitState(PatternLockerView.kt:272)

**Comment by ihsg** [comment]
无法复现
