### ISSUE TITLE
cellBeanList 最好使用懒加载，不然会产生未初始化问题

### ISSUE THREAD

**Issue by NicholasHzf** [ihsg/PatternLocker#39]
kotlin.UninitializedPropertyAccessException: lateinit property cellBeanList has not been initialized at com.github.ihsg.patternlocker.PatternLockerView.updateHitState(PatternLockerView.kt:270) at com.github.ihsg.patternlocker.PatternLockerView.handleActionDown(PatternLockerView.kt:225) at com.github.ihsg.patternlocker.PatternLockerView.onTouchEvent(PatternLockerView.kt:145)

**Comment by dhlie** [comment]
我也碰到这个问题了， 希望作者修复下

**Comment by oneapp1e** [comment]
看更新了2.6.0，但是这个问题为什么一直不修复呢

**Comment by ihsg** [comment]
2.6.1修复了哈，不好意思很久没看这个了，感谢反馈哈
