### ISSUE TITLE
请问手势绘制完成后，我怎样让绘制的数据不自动消失

### ISSUE THREAD

**Issue by qianzhihe86** [ihsg/PatternLocker#5]
我绘制完手势后，大概2-3秒后，绘制的手势会自动消失。请问我加一个确定按钮后，点击确定按钮前，要求手势不消失；点击按钮后，才让绘制手势消失，请问该怎么做？或者调用手势消失的方法时哪一个？同时不让他自动消失的方法时哪一个？谢谢

**Comment by ihsg** [comment]
@qianzhihe86 您好, 这个目前没有,你可以修改https://github.com/ihsg/PatternLocker/blob/master/library/src/main/java/com/github/ihsg/patternlocker/PatternLockerView.java 文件中的handleActionUp()方法, 如下代码注释掉,
//3. startTimer if needed
if (this.hitList.size() > 0) {
      startTimer();
}
需要清除手势的时候:调用clearHitState()方法

**Comment by ihsg** [comment]
@qianzhihe86 刚刚更新了一个版本,加了个“enableAutoClean” 标志量, 设置为false时不会主动清除,谢谢反馈

**Comment by qianzhihe86** [comment]
好的，谢谢，我上周已经在源码处自己添加一个标识处理了。不过你们能暴露一个方法更完善了。
