### ISSUE TITLE
手势连接中间点不会自动连接

### ISSUE THREAD

**Issue by BatterMan-Li** [ihsg/PatternLocker#6]
根据运行项目进行测试发现，如果你从第一个点滑动的移动的时候不经过第二点范围，滑动到第三点后，中间点没有自动添加连接上，这个功能和自带的滑动手势有区别，请问怎么样能添加或者提供实现的原理吗？

**Comment by ihsg** [comment]
@BatterMan-Li 你没碰到只要经过的也要连？ 如果是这样的话，只能通过计算才能做到

**Comment by BatterMan-Li** [comment]
@ihsg 请问如果实现上述效果复杂吗？如何实现能提供具体的实现方案吗?因为自带的手势密码都是做到这种效果的

**Comment by ihsg** [comment]
@BatterMan-Li 这个很简单的吧，每个圈圈都有一个（x, y）编号的，检查看编号之间是否有跳跃，如果有，自动加上就好了，比如（0，0）和（2，2），中间跳了一个（1，1），自动加上就好了！但是我感觉这样不太好，还是要用户自己设置了才连上比较好！

**Comment by BatterMan-Li** [comment]
很感谢你的回答，我已经做到了，网上搜索的方法和您提供一样的发自我的华为手机-------- 原始邮件 --------主题：Re: [ihsg/PatternLocker] 手势连接中间点不会自动连接 (#6)发件人：ihsg 收件人：ihsg/PatternLocker 抄送：BatterMan-Li ,Mention @BatterMan-Li 这个很简单的吧，每个圈圈都有一个（x, y）编号的，检查看编号之间是否有跳跃，如果有，自动加上就好了，比如（0，0）和（2，2），中间跳了一个（1，1），自动加上就好了！但是我感觉这样不太好，还是要用户自己设置了才连上比较好！

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ihsg/PatternLocker","title":"ihsg/PatternLocker","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ihsg/PatternLocker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ihsg in #6: @BatterMan-Li 这个很简单的吧，每个圈圈都有一个（x, y）编号的，检查看编号之间是否有跳跃，如果有，自动加上就好了，比如（0，0）和（2，2），中间跳了一个（1，1），自动加上就好了！但是我感觉这样不太好，还是要用户自己设置了才连上比较好！"}],"action":{"name":"View Issue","url":"https://github.com/ihsg/PatternLocker/issues/6#issuecomment-413493604"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ihsg/PatternLocker/issues/6#issuecomment-413493604",
"url": "https://github.com/ihsg/PatternLocker/issues/6#issuecomment-413493604",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [ihsg/PatternLocker] 手势连接中间点不会自动连接 (#6)",
"sections": [
{
"text": "",
"activityTitle": "**ihsg**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ihsg",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ihsg/PatternLocker\",\n\"issueId\": 6,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"ihsg/PatternLocker\",\n\"issueId\": 6\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/ihsg/PatternLocker/issues/6#issuecomment-413493604"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 336163542\n}"
}
],
"themeColor": "26292E"
}
]
